---
# tasks file for kube
- name: Add Kubernetes GPG Keys
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
    dest: /tmp/kubernetes-release.key
    mode: '0644'
- name: Convert GPG key to dearmored format
  ansible.builtin.command:
    cmd: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-release.key
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes Repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/kubernetes.list
    line: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /
    create: true
    mode: '0644'

- name: Install Kubeadm, Kubelet & Kubectl
  ansible.builtin.apt:
    pkg:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: true
  notify: 
    - Start Kubelet Service