apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: todo-secrets
  namespace: default
spec:
  encryptedData:
    MONGO_PASS: AgCy+t7oLcNgca3/zotFm3LDUKCpzUmH2Duv753lsWMIvI1d3F+R6cIveG/DaIylckLBbboNj1IbIN1cAfRXm8FC/txMRfOH68/jFk/hALpDtuGZNWEdyiZ5ZOo5ZKAkJkHn87YkH0coRt8zCMe38IzLcChEhCsc9hkRyv+/RdzZ36ZnIQwl7QKHCUtfErlY7Z9WqITeQ8VTPpADF4UpnFmcp6LTmXFVBuRFv/SM/XFknYhI7jgDFAM/vvKY2NYBkd891YcD5FU7WNZO2bi+0wU9uLovgkPlaFpV7v+POJLB+Vac6CURDrcpDiqhBxiYU7gay9VF11eA7d/VCwgrVJ3gspVxhVqP1+TGOHXrNpnwvXHmpXPGYt/LmeNMpmk+yPrrVVVqoMSIP4wSMqgELY3NkjqXx8NM5OVJFN5TZCr0a1hKX8IoIl21mKhK6snIheMGJ8MU6cjDrc8ZCYQPN/p/0pLOgEQIdlAalVHLxVdtyKwAYM4gmP6VOXPnQLfGqSvS91dK4U+VZVdd/i3cZbOERCpE4vTLY35ZLg6yXVIFu9E2GOUYU5AjSOrOgo6OEUZbWcsqgxZEDf6VxNd/V1QdV5lxa+TajKVcO9o/lptA6lVbxFj/9kv9WszX48hvDig7ezHL6UnTFI4d/gITAvxDOz+zskcUYeIbf+opXGb1enCv+6ZcaObzgOf+teP7XWqnDUqEfzAzDljtZU++LA==
    MONGO_USER: AgAhcgREBeg3HPdiRqW+3vnVHgas1usgvpsLp5Uig+2wLyN/mYtCw6IMcaem0GWJD7dTpYiZl6pH+AAzS0rhEJN7PT5xY7q+iWaby/7a0ACao6zYagIgw7Nyi6KjJ7tYvYfbAhR8T4qzSaWT4bE9gXaP2OPalxEW9Rcp0iNC8KpPmI6zotfQvwYefEAOXfSO46iGQT5Hn8JZaRXtgobjdxQX8X4D0XKnGspMHCsM7Soa7ICJgALtZXXqhNaJd1mPQiK6MpCPtKZAzbA1Zc4JVoPw8OMzRiqOHUEvgUj0h2H4s5zyWeccPJucqPpfAQzaZ61TUIjC/1IofyMekvV5drz8N0Oazx2TPty0h607fJHht8kvLKhUsN9+tTIm7Y/RNywaEsVWEZj01p7Ou+6NWQ8W0iMWZKpBbx2TFH0EIhCdjUz3IEdc9GXuXkhwioRg6VYzojw7sje+q9zsxccVYNXvZuV5/agjbYVaBrJqp+yIPjiqCbuFKAu5cvC4jvY9L5G4QtPySCFXs3NmEqXkpTnZtczk3aWSjLXdSD/Om6+OaGfIBnBF0lF1BYG/o8ks51J0BiLZ/rVkpjb5rWzjn8UnnR86cL36f9g2xDheXglPC3AuvMZkfNfwn6SgdVJPIaa47elEvHANbOWFQVegjLQUm9bq1DeufMLc9RUit75YuTRv5Fhm4gV8eG1sYq0C8Ni6TwA7Gw==
  template:
    metadata:
      creationTimestamp: null
      name: todo-secrets
      namespace: default

