apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: todo-secrets
  namespace: default
spec:
  encryptedData:
    MONGO_Pass: AgBh2Rid8XfxcIxJw7zZUB4eaG7YgbCjHTxM1bAlCuwA7Zyton31mZy2CYUHNQzLzMHyFNjcRhEuGTfBPVq6zTnlc/SFFMXRmGzIvvo7veBDdR1GHGWf7v+nyPFFa8734gGs65DYJj1C0YSwSS4mgxVXZnXbnKalrYKBMmvR2u23+xEgKyVjMWhZbbnKWWZaj/TYqZ0ki5CP/2Xc3SodrYz6RxafbcB2TW1HpJoep8r0OP0aaQ/DfmBcRTC6k0ldzqgN0QdAq5fF25tLS4ygUUjPpgEMQavQU/LCg3PXpnsIWrhrc0mVsbRMUi3cRyE+6TmiWa6ffDV8bufzTkv2QHps4R8riz1uGbwNRHVdjlE9cIJSvX5TIvA3u7ME93D5HquHalaSqoagdylBSs76ZC+sI4MbHUWS7xySgYVt4j1KV3f3cGgdn2Vq/An4aEesWv5NN56RWJ8vhqyJnUbuD90vkJxeMZEjGFl4tKtWIMNoaF0Nyc6p6G6uUegJqySb6XG9V6UqRqsEqPSG0+FTSfnyiyRUhue+XMXHh3rk9DLzMZXEU6kw3tn6NXcMdeIatYX2fPdIOmVragGk6LvcHV2keMqIipAwjJFhgRKhvCup7DGgey7t6jYdBdXzuKsmOUblX+6Y0L2mOpNW69UUNOlElpBYnou+73OSzCfUBGxBH/M647UBp+ZzpOX2ksgP3eRNdt21SN1V5Fehshtxxg==
    MONGO_USER: AgAv/WcQO0xuZqfbbJhVFtIYC8z1MW7WimQWXaPU4KPP+pvTazd421LaVH5EkX3Ts0US4aFiJhj9JIWm17RfwmmaYsdN2lEk4KJNfYrSLpWip6fSJyWcjDrAYYRYr6bLpNs1vaPrKt9mP2YRfS+xcx0++VA2YNFmwxcm8dtD5tmd7ElRn0w/MWNnWwl6uJAKRfBRJEZhXTZqFNpFpCs1tYfKgYQbJUi8Ppqspp9UQWvVNdLuF0oT17hS2dZ4M8gsb+S4jbczvfzuFcPwqXimgNzH3UxRUNFPFupZ7cWETJOAUPIMLLUU10iHKmdfY9dEocloTvvfMAe4oIP+P9/IQkqVLMeAEpgoDxvwu61uvPPcEAxMW0a1LwCewpXChh1iR2qTVC1yTEBoDpqEAjTp8YcmIcIFmewFPaqwkgnKdrPjTL3kSlTXCTkcyJKOGrrR6M5+hvt9eLJg0+Ayzb42zFAFdbp2vVLsjIMgTqI7iH/WBEpjSAHeyM5MUOU5/E8Cx7ieWZPehVeWgJhJMo9RBLXUqpHMDBSaoROznlmP+Rki0OZnGRZ0f7JZM+sIk7pIHomZKydtH7pfV6xMjqgYeCoTcC8JKV1jBCGYH++RBXc3O+wXCrXMoyrtVjMvWE7sY0oqHUFWqslWmeUikAR2aXjZb57J0Wfxi6dU3sW8cZK7M5ezvFoz4MLTQv0t4NbMOH1+MXBsGw==
  template:
    metadata:
      creationTimestamp: null
      name: todo-secrets
      namespace: default

